name: Testing Only

on:
  pull_request:
    branches:
      - main  # Runs when a PR is opened to the main branch
  push:
    branches:
      - dev  # Runs when code is pushed to the dev branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests
        run: |
          npm test

      - name: Run Linting (Code Quality Check)
        run: |
          npm run lint
